FROM python:3.8.7-slim-buster

WORKDIR /app



ENV PYTHONDONTWRITEBYTECODE 1

ENV PYTHONUNBUFFERED 1

RUN apt-get update \
    && apt-get -y install netcat gcc postgresql \
    && apt-get clean
RUN apt-get install -y python-psycopg2 libpq-dev 

       
RUN pip3 install --upgrade setuptools
RUN pip install --upgrade pip


COPY ./requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt

COPY . /app
